CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(200) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL UNIQUE,
    hashed_password VARCHAR NOT NULL,
    role VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS password_reset (
    phrase VARCHAR(200) PRIMARY KEY,
    email VARCHAR(200) NOT NULL UNIQUE
);
