name: Deploy

# run on push to master (includes when PR is merged) or when manually triggered
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Production Server
    runs-on: ubuntu-latest
    steps:
      - name: ssh remote command to trigger deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.DEPLOY_SCRIPT_LOCATION }}
            sh deploy.sh
