name: Test

# run on push to any branches except master or test-deploy or when manually triggered
on:
  push:
    branches-ignore:
      - "master"
      - "test-deploy"
  workflow_dispatch:

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - name: run tests
        uses: ./.github/workflows/test_caller.yml
        secrets:
          CONFIG: ${{ secrets.CONFIG }}